from distutils.core import setup
setup(name='epubbuilder',
      version='1.0',
      description='fork of http://code.google.com/p/python-epub-builder/ to programmatically build EPUB books.',
      author='Jonathan Butcher',
      author_email='footley@gmail.com',
      url='https://github.com/footley/md2ebook',
      py_modules=['epubbuilder'],
      data_files=[('templates', ['container.xml', 
                                 'content.opf',
                                 'image.html',
                                 'title-page.html',
                                 'toc.html',
                                 'toc.ncx',
                                 ]),
                  ('test-files', ['revenge.500x800.jpg']),
                  ('epubcheck-3.0b5', ['COPYING.txt',
                                       'README.txt',
                                       'epubcheck-3.0b5.jar',
                                       ]),
                  ('epubcheck-3.0b5/lib', ['batik-css-1.7.jar',
                                           'batik-license.txt',
                                           'batik-util-1.7.jar',
                                           'commons-compress-1.2.jar',
                                           'commons-compress-license.txt',
                                           'jing-20120227.jar',
                                           'jing-license.txt',
                                           'sac-1.3.jar',
                                           'sac-license.txt',
                                           'saxon-9.1.0.8.jar',
                                           'saxon-license.txt',
                                           ]),
                 ],
      )

